---
title: "Data 602 Project David"
output: 
  pdf_document:
    latex_engine: xelatex
  html_notebook: default
date: "2024-10-11"
---

```{r}
data1=read_excel("C:/Users/Owner/Downloads/fp-historical-wildfire-data-2006-2023.xlsx")

```
```{r}
head(data1)
```
```{r}
summary(data1)
```

```{r}
reglarge=lm(formula=data1$uc_hectares~data1$temperature+data1$relative_humidity+data1$wind_speed)
summary(reglarge)
regsub1=lm(formula=data1$uc_hectares~data1$temperature)
regsub2=lm(formula=data1$uc_hectares~data1$relative_humidity)
regsub3=lm(formula=data1$uc_hectares~data1$wind_speed)
summary(regsub1)
summary(regsub2)
summary(regsub3)
```
```{r}
reg_df=data.frame(uc_hectares=data1$uc_hectares,temperature=data1$temperature,relative_humidity=data1$relative_humidity,wind_speed=data1$wind_speed)
reg_cor= round(cor(reg_df,use = "complete.obs"), 2)
reg_cor

```
```{r}
ggplot(reg_df, aes(x=uc_hectares, y =temperature )) + 
  geom_point(color = "red") + stat_smooth(method = "lm", 
                                          formula = y ~ x, geom = "smooth")
ggplot(reg_df, aes(x=uc_hectares, y =relative_humidity )) + 
  geom_point(color = "red") + stat_smooth(method = "lm", 
                                          formula = y ~ x, geom = "smooth")
ggplot(reg_df, aes(x=uc_hectares, y =wind_speed )) + 
  geom_point(color = "red") + stat_smooth(method = "lm", 
                                          formula = y ~ x, geom = "smooth")
```
```{r}
qqnorm(reglarge$residuals)
qqline(reglarge$residuals)
```
```{r}
ggplot(data = reg_df, aes(x = temperature)) +
  geom_histogram(color='blue')
ggplot(data = reg_df, aes(x = relative_humidity)) +
  geom_histogram(color='blue')
ggplot(data = reg_df, aes(x = wind_speed)) +
  geom_histogram(color='blue')
```

















